import router from '@adonisjs/core/services/router'

const AdminController = () => import('#controllers/admin_controller')
const StockController = () => import('#controllers/admin/stock_controller')
const ProviderController = () => import('#controllers/provider_controller')
const OrderController = () => import('#controllers/admin/order_controller')
const CustomerController = () => import('#controllers/admin/customer_controller')
const MessageController = () => import('#controllers/message_controller')
const RegistryController = () => import('#controllers/registry_controller')
const CartItemController = () => import('#controllers/cart_item_controller')
const SettingController = () => import('#controllers/setting_controller')
const ShowcaseController = () => import('#controllers/showcase_controller')
const ReceiptsController = () => import('#controllers/receipts_controller')
const CustomerOrdersController = () => import('#controllers/admin/customer_orders_controller')
const CategoriesController = () => import('#controllers/categories_controller')

export default function adminRoutes() {
  router.get('/', [AdminController, 'index']).as('home')
  router.get('/stock/view', [StockController, 'view']).as('stock.view')
  router.resource('/stock', StockController).as('stock')
  router.post('/stock/:id/image', [StockController, 'uploadImage']).as('stock.uploadImage')
  router.get('/customers/view', [CustomerController, 'view']).as('customers.view')
  router.resource('/customers', CustomerController).as('customers')
  router.resource('/customers/:customerId/orders', CustomerOrdersController).as('customers.orders')
  router.resource('/messages', MessageController).only(['index', 'show', 'destroy']).as('messages')
  router
    .resource('/providers', ProviderController)
    .only(['index', 'edit', 'update'])
    .as('providers')
  router.get('/providers/list', [ProviderController, 'list']).as('providers.list')
  router
    .patch('/providers/:id/products-publication', [ProviderController, 'updateProductsPublication'])
    .as('providers.updateProductsPublication')
  router
    .resource('/registries', RegistryController)
    .only(['index', 'edit', 'destroy'])
    .as('registries')
  router.resource('/orders', OrderController).as('orders')
  router.get('/orders/:id/print', [OrderController, 'print']).as('orders.print')
  router.resource('/cart-items', CartItemController).only(['update'])
  router.get('/settings/view', [SettingController, 'view']).as('settings.view')
  router.resource('/settings', SettingController).as('settings')
  router.get('/showcases/create', [ShowcaseController, 'create']).as('showcases.create')
  router.post('/showcases-order', [ShowcaseController, 'order']).as('showcases.order')
  router
    .resource('/showcases', ShowcaseController)
    .only(['index', 'store', 'destroy', 'edit', 'update'])
    .as('showcases')
  router.get('/showcases/list', [ShowcaseController, 'list']).as('showcases.list')
  router.resource('/receipts', ReceiptsController)
  router.resource('/categories', CategoriesController).as('categories')
  router.get('/categories-list', [CategoriesController, 'list']).as('categories.list')
}
